<a href="https://colab.research.google.com/github/landofgiurla/data-science-from-scratch/blob/master/zoomcamp_session_01_homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Question 1

In [128]:
import numpy as np
np.__version__

'1.21.6'

# Question 2

In [3]:
from google.colab import files
uploaded = files.upload()

Saving data.csv to data.csv


In [4]:
import pandas as pd

In [5]:
data = pd.read_csv('data.csv')
df = pd.DataFrame(data)

In [6]:
df.shape

(11914, 16)

# Question 3

In [148]:
make = df.Make

In [149]:
make.value_counts().head(3)

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

# Question 4

In [91]:
Audi_series = df[df["Make"] == 'Audi']

In [93]:
Audi_series.shape

(328, 16)

In [94]:
Audi_series.value_counts().nunique()

3

# Question 5

In [97]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

## Question 6

In [150]:
cil = df["Engine Cylinders"]

In [151]:
cil.describe()

count    11884.000000
mean         5.628829
std          1.780559
min          0.000000
25%          4.000000
50%          6.000000
75%          6.000000
max         16.000000
Name: Engine Cylinders, dtype: float64

In [152]:
cil.median()

6.0

In [153]:
freq_value = cil.mode()

In [154]:
print(freq_value)

0    4.0
dtype: float64


In [155]:
cil.isnull().sum()

30

In [15]:
cil.describe()

count    11884.000000
mean         5.628829
std          1.780559
min          0.000000
25%          4.000000
50%          6.000000
75%          6.000000
max         16.000000
Name: Engine Cylinders, dtype: float64

In [156]:
new_cil = cil

In [157]:
new_cil.describe()

count    11884.000000
mean         5.628829
std          1.780559
min          0.000000
25%          4.000000
50%          6.000000
75%          6.000000
max         16.000000
Name: Engine Cylinders, dtype: float64

In [158]:
b = new_cil.fillna(4.0)

In [159]:
b.describe()

count    11914.000000
mean         5.624727
std          1.780189
min          0.000000
25%          4.000000
50%          6.000000
75%          6.000000
max         16.000000
Name: Engine Cylinders, dtype: float64

In [160]:
b.isnull().values.any()

False

In [162]:
b.median()

6.0

In [49]:
b.describe()

count    11914.000000
mean         5.624727
std          1.780189
min          0.000000
25%          4.000000
50%          6.000000
75%          6.000000
max         16.000000
Name: Engine Cylinders, dtype: float64

## Question 7

In [88]:
Lotus_series = df[df["Make"] == 'Lotus']

In [89]:
Lotus_series.shape

(29, 16)

In [98]:
lotus_table = Lotus_series [["Engine HP","Engine Cylinders"]]

In [101]:
lotus_table

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0
3917      189.0               4.0
3918      217.0               4.0
3919      217.0               4.0
4216      350.0               8.0
4217      350.0               8.0
4218      350.0               8.0
4257      400.0               6.0
4258      400.0               6.0
4259      276.0               6.0
4260      276.0               6.0
4261      276.0               6.0
4262      345.0               6.0
4263      345.0               6.0
4264      276.0               6.0
4265      345.0               6.0
4266      276.0               6.0
4267      345.0               6.0
4268      276.0               6.0
4292      257.0               4.0
4293      240.0               4.0
4294      240.0               4.0
4295      240.0               4.0
4296      257.0               4.0
4297      257.0               4.0

In [110]:
lotus_unique = lotus_table.drop_duplicates()

In [114]:
lotus_unique.shape

(9, 2)

In [115]:
lotus_unique

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [117]:
x = lotus_unique.values

In [118]:
x

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [119]:
x.shape

(9, 2)

In [132]:
xTx = np.matmul(x.T,x)

In [133]:
xTx.shape

(2, 2)

In [137]:
inv_xTx = np.linalg.inv(xTx)

In [134]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

In [135]:
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [144]:
q = np.matmul(inv_xTx, x.T)

In [145]:
q

array([[-1.31950096e-03,  2.84443321e-04,  2.29134897e-04,
        -4.18763778e-03,  4.46417989e-03, -2.39406462e-03,
         1.42221660e-03,  2.44147184e-03,  1.50122864e-03],
       [ 8.60893170e-02,  7.36567735e-04,  3.67976598e-03,
         2.54588185e-01, -2.13748621e-01,  1.51207962e-01,
        -5.18727169e-02, -1.14048164e-01, -6.40137937e-02]])

In [146]:
w = np.matmul(q,y)

In [147]:
w


array([  4.59494481, -63.56432501])